tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "on-tertiary-fixed-variant": "#802a00",
                "secondary-fixed": "#cbe7f5",
                "secondary-fixed-dim": "#afcbd8",
                "surface-variant": "#e1e3e4",
                "on-error-container": "#93000a",
                "surface-container": "#edeeef",
                "primary-fixed-dim": "#a7c8ff",
                "on-secondary-container": "#4e6874",
                "surface-bright": "#f8f9fa",
                "tertiary-fixed": "#ffdbcf",
                "outline": "#737780",
                "error": "#ba1a1a",
                "background": "#f8f9fa",
                "primary-container": "#003366",
                "on-error": "#ffffff",
                "on-primary-fixed": "#001b3c",
                "primary-fixed": "#d5e3ff",
                "on-surface-variant": "#43474f",
                "surface-container-lowest": "#ffffff",
                "surface-container-low": "#f3f4f5",
                "on-tertiary": "#ffffff",
                "inverse-on-surface": "#f0f1f2",
                "surface-container-highest": "#e1e3e4",
                "secondary": "#48626e",
                "primary": "#001e40",
                "on-background": "#191c1d",
                "surface-container-high": "#e7e8e9",
                "inverse-surface": "#2e3132",
                "secondary-container": "#cbe7f5",
                "inverse-primary": "#a7c8ff",
                "on-tertiary-container": "#ff6f33",
                "on-primary": "#ffffff",
                "tertiary": "#3c0f00",
                "on-secondary": "#ffffff",
                "on-secondary-fixed": "#021f29",
                "tertiary-fixed-dim": "#ffb59a",
                "surface-dim": "#d9dadb",
                "on-primary-container": "#799dd6",
                "surface": "#f8f9fa",
                "on-surface": "#191c1d",
                "error-container": "#ffdad6",
                "on-tertiary-fixed": "#380d00",
                "outline-variant": "#c3c6d1",
                "on-primary-fixed-variant": "#1f477b",
                "on-secondary-fixed-variant": "#304a55",
                "surface-tint": "#3a5f94",
                "tertiary-container": "#5f1d00"
            },
            "borderRadius": {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            "fontFamily": {
                "headline": ["Public Sans", "PingFang TC", "Noto Sans TC", "sans-serif"],
                "body": ["Inter", "PingFang TC", "Noto Sans TC", "sans-serif"],
                "label": ["Inter", "PingFang TC", "Noto Sans TC", "sans-serif"]
            }
        },
    },
}
